name: CI-CD-Iniciativa-Kubernetes
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  meu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USUARIO }}
          password:  ${{ secrets.DOCHERHUB_PWD }}
