name: CI-CD-Iniciativa-Kubernetes
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  meu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USUARIO }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      
      - name: Docker Build and Push
        uses: docker/build-push-action@2.7.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            marciozhu/rotten-potatoes:latest
            marciozhu/rotten-potatoes:${{ github.run_number }}
            
